name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        FOO: bar 
      run: |
        set -e
        env
        whoami
        ls -la /usr/local/bin
        ls -la /usr/bin
        df -h
