name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.2.1'
    - run: |
        java -version
        which native-image
