name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print
      run: |
        set -e
        date > date.txt
    - name: Show
      run: |
        set -e
        cat date.txt
